### PR TITLE
Switch to using the COM Interfaces API to interact with the wallpapers

### PR DESCRIPTION
**Pull request by beyluta**
All the changes have been well-tested and should work with the same dependencies under Win10 machines.

- Remove old C files
- Adapt Build script
- Use the COM Interfaces API
- Implements the "Scaling" option that MacOS has

The source was changed from C  to C++. I justify this change because: this PR will greatly improve the maintainability of the codebase, allow for further optimization, and new features to be quickly built with the help of the COM API.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks. I don't have a Windows VM. Would you be able to compile the binary, ZIP it, and share it here? (Just drag it into the comment field)

**Comment by beyluta** [comment]
[binary.zip](https://github.com/sindresorhus/win-wallpaper/files/10538786/binary.zip)
Here you go.

**Comment by sindresorhus** [comment]
Could you build another binary with the latest changes in `main` branch? So it gets the correct version number.

**Comment by beyluta** [comment]
> Could you build another binary with the latest changes in `main` branch? So it gets the correct version number.

Sure.
[binary_2.0.0.zip](https://github.com/sindresorhus/win-wallpaper/files/10543159/binary_2.0.0.zip)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/win-wallpaper/releases/tag/v2.0.0

**Pull request merged**
